title:        systems seminar
tagline:      'Systems Seminar'
description:  'EPFL IC Systems seminar'
author:
  name:       Baris Kasikci
  email:      baris.kasikci@epfl.ch
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     3