# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Baris Kasikci's Home Page
tagline:
description:      'I am interested in making computer systems more reliable, secure, and efficient'
#url:		  https://homes.cs.washington.edu/
baseurl:          /~baris/

#

author:
  name:           Baris Kasikci
  url:            https://homes.cs.washington.edu/~baris

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
#paginate:        5

# Custom vars
version:

github:
  repo: